[package]
name = "wallhelper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
execute = "0.2.12"
rand = "0.8.5"
toml = "0.7.6"
